### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by ekang4703** [Alamose/Custom-Lost-Cities-Generation#1]
How do I download this and where would I put all the files? Is downloading the mods needed for some of the buildings enough for them to load if I dumb all the files into the config folder?

**Comment by Alamose** [comment]
Yes the mod is required as this addition only adds a few new building types using the existing mod's generation. It has been so long since I've written this that I am unsure what mod versions are supported.

**Comment by ekang4703** [comment]
but apart from the buildings that require mods, do you remember how one would go about installing the rest of the files, would I need to completely replace every single file in the config folder?

**Comment by ekang4703** [comment]
for example, if I wanted to add all the vanilla buildings, would i have to make json files for every single building, then have the general.cfg pull the data from every single one? would the code look like this in the file, "$lostcities/userassets.json". Also, in the read me it says to rename the file to userassets.json, but what if the cfg already has the code like the line i provided above already in the file. It was there when I first downloaded the mod and I don't want to mess anything up. Would i just name the files to somethign like building1.json and have the code in the cfg file say something like $lostcities/building1.json" and so forth?

**Comment by Alamose** [comment]
If I remember correctly this just hooks into the existing generation and adds things without overwriting the base buildings. Though for the generator to recognize them I had to edit some of the mod's files so that they would be registered. I would suggest installing the mod, loading minecraft up once, then overwrite any files it makes with one's I have in this directory. I'm guessing this was for 1.12 since that was the popular version for pack dev at the time.

**Comment by ekang4703** [comment]
yes it is, im running 1.12.2, would any of the loot change? I implemented custom loot tables, would I have to redo that process with the new buildings again?

**Comment by ekang4703** [comment]
so in the lost cities folder, would I simply add all the files, rename them something like building1 to building2 and so on, then in the general.cfg file have the code look something like this? 
S:assets <
        $lostcities/conditions.json
        /assets/lostcities/citydata/palette.json
        /assets/lostcities/citydata/palette_desert.json
        /assets/lostcities/citydata/palette_chisel.json
        /assets/lostcities/citydata/palette_chisel_desert.json
        /assets/lostcities/citydata/highwayparts.json
        /assets/lostcities/citydata/railparts.json
        /assets/lostcities/citydata/monorailparts.json
        /assets/lostcities/citydata/buildingparts.json
        /assets/lostcities/citydata/library.json
        $lostcities/userassets.json
        $lostcities/building1.json
        $lostcities/building2.json
        $lostcities/building3.json
     >

**Comment by ekang4703** [comment]
Would it be a problem to leave the original userassets.json code there?

**Comment by ekang4703** [comment]
everything up to userassets.json in the code i provided is the stuff that is from the mod with zero changes btw.

**Comment by Alamose** [comment]
Looks like the "HW" (was originally written for a pack called Haunted Wastelands) folder contains everything besides some of the pallet swaps and the Readme in there has the most detailed info on what to do to add it. I do know in the config file the assets list is very dependant on load order and userassets.json needs to be last. You won't be able to add this while keeping the old userassets.json file as there are some things that need to be added to it for thf mod to register some of the building layouts.
